### ISSUE TITLE
Bulk network creation for ISC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#11]
ISC (https://peeringdb.com/org/1330) has roughly 50 networks to add to their organisation. Doing this by hand is tedious. Please find attached a file with TAB separated tuples of (network names, ASN). All of these should be added if not already there and linked to org/1330
[ISC-F-ROOT.txt](https://github.com/peeringdb/admincom/files/736807/ISC-F-ROOT.txt)

**Comment by job** [comment]
Here is a slightly revised list. I've removed the Private ASN (as65432).
[ISC-F-ROOT-v2.txt](https://github.com/peeringdb/admincom/files/736826/ISC-F-ROOT-v2.txt)

**Comment by arnoldnipper** [comment]
Shouldn't private ASN been dropped automatically?

**Comment by job** [comment]
@arnoldnipper as soon as this https://github.com/peeringdb/peeringdb/issues/102 is deployed, yes :-)

**Comment by grizz** [comment]
We have no existing code that would be helpful for this, so it should start as an issue at https://github.com/peeringdb/peeringdb/issues I think.

**Comment by arnoldnipper** [comment]
My understanding was that you already have code available to bulk add all the ASN. This would be a sub case for that tool. Right?

**Comment by arnoldnipper** [comment]
Customer meanwhile sent in requests via DeskPRO
