### ISSUE TITLE
502 Bad gateway when affiliating to an ASN

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#134]
User gets 502 Bad gateway when affiliating to ASN 27292
![20180525 peeringdb 01](https://user-images.githubusercontent.com/16888757/40561620-2a02e432-605e-11e8-97e6-455e67eebec9.png)

**Comment by ccaputo** [comment]
This should now be fixed.  Please confirm.

**Comment by arnoldnipper** [comment]
Confirmed
