### ISSUE TITLE
logging to verification queue broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#135]
Last entry at https://peeringdb.com/cp/peeringdb_server/verificationqueueitem/ is from May 25, 2018, 1:57 p.m., however I see tickets created later

**Comment by job** [comment]
I cannot reproduce this. I created "Snijders IX" and it showed up in the verification queue.

Can you test yourself and confirm there actually is an issue?

**Comment by arnoldnipper** [comment]
Sorry ... pls disregard
