### ISSUE TITLE
batch renumbering for NAPAfrica IX Johannesburg

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#14]
User Andrew Owens says in DeskPRO ticket #3211:

NAPAfrica IX Johannesburg (ID: 592) completed IP renumbering at the exchange at the beginning of February.

Some of our members have updated their records to show the new IP addresses, but we are struggling to get all members to do so - This is causing issues with members that use PeeringDB for automation.

Previously our peering prefix was 196.46.25.0/24. The new peering prefix is 196.60.8.0/23
We wanted to find out whether it would be possible for you to manually change the addresses for those members that have not done so yet? The last octet of all member addresses remains the same in 196.60.8 (i.e. 196.46.25.X --> 196.60.8.X)

**Comment by arnoldnipper** [comment]
Andrew added:

For reference, you can find our member list in Euro-IX JSON format here: http://ixpmanager.napafrica.net/apiv1/member-list/list/key/gHcHxUwewihhydSy6KU0XoPuYtfrCl0rmzYXV35jmpoTs8nK

There is a bug in the version we use which excludes CPT and DBN members if they are not a member at JHB as well, but all JHB records are 100%

**Comment by vegu** [comment]
Done

Log
-----

ixpfx: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.0/24 -> 196.60.8.0/24
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.140 -> 196.60.8.140
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.173 -> 196.60.8.173
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.174 -> 196.60.8.174
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.160 -> 196.60.8.160
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.148 -> 196.60.8.148
netixlan: NAPAfrica IX Cape Town <IXLAN:597> 196.46.25.13 -> 196.60.8.13
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.169 -> 196.60.8.169
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.153 -> 196.60.8.153
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.194 -> 196.60.8.194
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.184 -> 196.60.8.184
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.152 -> 196.60.8.152
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.155 -> 196.60.8.155
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.158 -> 196.60.8.158
netixlan: NAPAfrica IX Cape Town <IXLAN:597> 196.46.25.28 -> 196.60.8.28
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.186 -> 196.60.8.186
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.222 -> 196.60.8.222
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.229 -> 196.60.8.229
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.138 -> 196.60.8.138
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.231 -> 196.60.8.231
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.216 -> 196.60.8.216
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.238 -> 196.60.8.238
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.250 -> 196.60.8.250
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.252 -> 196.60.8.252
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.248 -> 196.60.8.248
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.196 -> 196.60.8.196
netixlan: NAPAfrica IX Durban <IXLAN:969> 196.46.25.72 -> 196.60.8.72
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.132 -> 196.60.8.132
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.225 -> 196.60.8.225
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.242 -> 196.60.8.242
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.144 -> 196.60.8.144
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.253 -> 196.60.8.253
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.230 -> 196.60.8.230
netixlan: NAPAfrica IX Durban <IXLAN:969> 196.46.25.83 -> 196.60.8.83
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.141 -> 196.60.8.141
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.139 -> 196.60.8.139
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.200 -> 196.60.8.200
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.197 -> 196.60.8.197
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.113 -> 196.60.8.113
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.120 -> 196.60.8.120
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.145 -> 196.60.8.145
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.233 -> 196.60.8.233
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.118 -> 196.60.8.118
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.102 -> 196.60.8.102
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.98 -> 196.60.8.98
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.99 -> 196.60.8.99
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.247 -> 196.60.8.247
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.90 -> 196.60.8.90
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.107 -> 196.60.8.107
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.127 -> 196.60.8.127
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.213 -> 196.60.8.213
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.89 -> 196.60.8.89
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.167 -> 196.60.8.167
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.35 -> 196.60.8.35
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.103 -> 196.60.8.103
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.193 -> 196.60.8.193
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.95 -> 196.60.8.95
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.81 -> 196.60.8.81
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.77 -> 196.60.8.77
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.78 -> 196.60.8.78
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.114 -> 196.60.8.114
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.236 -> 196.60.8.236
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.226 -> 196.60.8.226
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.227 -> 196.60.8.227
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.162 -> 196.60.8.162
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.143 -> 196.60.8.143
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.73 -> 196.60.8.73
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.185 -> 196.60.8.185
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.80 -> 196.60.8.80
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.100 -> 196.60.8.100
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.197 -> 196.60.8.197
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.198 -> 196.60.8.198
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.198 -> 196.60.8.198
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.198 -> 196.60.8.198
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.191 -> 196.60.8.191
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.67 -> 196.60.8.67
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.154 -> 196.60.8.154
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.182 -> 196.60.8.182
netixlan: NAPAfrica IX Johannesburg <IXLAN:1247> 196.46.25.69 -> 196.60.8.69
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.255 -> 196.60.8.255
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.210 -> 196.60.8.210
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.237 -> 196.60.8.237
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.49 -> 196.60.8.49
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.56 -> 196.60.8.56
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.43 -> 196.60.8.43
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.39 -> 196.60.8.39
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.50 -> 196.60.8.50
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.65 -> 196.60.8.65
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.116 -> 196.60.8.116
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.116 -> 196.60.8.116
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.46 -> 196.60.8.46
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.33 -> 196.60.8.33
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.172 -> 196.60.8.172
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.23 -> 196.60.8.23
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.21 -> 196.60.8.21
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.21 -> 196.60.8.21
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.24 -> 196.60.8.24
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.15 -> 196.60.8.15
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.16 -> 196.60.8.16
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.180 -> 196.60.8.180
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.19 -> 196.60.8.19
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.230 -> 196.60.8.230
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.61 -> 196.60.8.61
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.213 -> 196.60.8.213
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.243 -> 196.60.8.243
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.70 -> 196.60.8.70
netixlan: NAPAfrica IX Johannesburg <IXLAN:592> 196.46.25.47 -> 196.60.8.47
