### ISSUE TITLE
Can't create new org, though org is not yet there

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#15]
Software thinks of a dup. However "Telewizja Kablowa Hajnowka, Kiedys, Kiryluk, SJ" is not yet registered, "Telewizja Kablowa BART-SAT" is.

**Comment by vegu** [comment]
It is there: https://www.peeringdb.com/cp/peeringdb_server/organization/?q=Telewizja+Kablowa+Hajnowka%2C+Kiedys%2C+Kiryluk%2C+SJ&status=all

Shows it was created earlier today

**Comment by arnoldnipper** [comment]
Thanks a lot, Stefan ... one of these moments when PeeringDB GUI is not showing the org though refreshing zillion times
