### ISSUE TITLE
Merge fac 1255 > 46

### ISSUE THREAD

**Issue by martzuk** [peeringdb/admincom#156]
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:18652,vis:7

https://peeringdb.com/fac/1255 > https://peeringdb.com/fac/46

**Comment by vegu** [comment]
Took care of this one in order to test the 2.9.3 rollout, will send instructions to ac list shortly.

**Comment by arnoldnipper** [comment]
https://peeringdb.com/fac/1255 no longer exists
