### ISSUE TITLE
Merge duplicate fac/2215, fac/1971 and fac/1201 into fac/3092

### ISSUE THREAD

**Issue by NoelleKenny** [peeringdb/admincom#172]
Combining DataLine's OST data centers, as confirmed by the organization's user via. deskpro ticket ID 18772.  Pavel Zavyalov from DataLine confirmed that they have the same location and connectivity and should be named DataLine OST.

https://peeringdb.com/fac/2215
https://peeringdb.com/fac/1971
https://peeringdb.com/fac/1201
https://peeringdb.com/fac/3092

**Comment by arnoldnipper** [comment]
Merging facilities 2215 -> 3092
Merging DataLine (2215) ..
- netfac NetworkFacility-netfac26914
soft deleting DataLine

Merging facilities 1971 -> 3092
Merging Moscow DATALINE OST (1971) ..
- netfac NetworkFacility-netfac15389
- netfac NetworkFacility-netfac17952
- netfac NetworkFacility-netfac18639
- netfac NetworkFacility-netfac19074
- netfac NetworkFacility-netfac25318
- ixfac InternetExchangeFacility-ixfac951
soft deleting Moscow DATALINE OST

Merging facilities 1201 -> 3092
Merging Dataline Borovaya (1201) ..
- netfac NetworkFacility-netfac9537 : connection already exists at target, skipping.
- netfac NetworkFacility-netfac9680
- netfac NetworkFacility-netfac10268
- netfac NetworkFacility-netfac11123
- netfac NetworkFacility-netfac11657
- netfac NetworkFacility-netfac12368
- netfac NetworkFacility-netfac12620
- netfac NetworkFacility-netfac14191
- netfac NetworkFacility-netfac17160
- netfac NetworkFacility-netfac17597
- netfac NetworkFacility-netfac20712 : connection already exists at target, skipping.
- netfac NetworkFacility-netfac23644
- netfac NetworkFacility-netfac25827
- netfac NetworkFacility-netfac26969
- netfac NetworkFacility-netfac27019
- ixfac InternetExchangeFacility-ixfac1184
- ixfac InternetExchangeFacility-ixfac1437
soft deleting NetworkFacility-netfac9537
soft deleting NetworkFacility-netfac20712
soft deleting Dataline Borovaya
