### ISSUE TITLE
Including images in "Notes" field

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#191]
[ https://peeringdb.deskpro.com/agent/#app.tickets,inbox:unassigned,t.o:18900,vis:6 ]

User writes: "I played around a bit with the markdown formatting for the "Notes" field.

After including an image and clicking "save", the image is displayed as intended (see dx-pdb1.png) but after reloading the page, only the markdown code is shown (see dx-pdb2.png).

Maybe including images is not encouraged anyway"

<img width="542" alt="dx-pdb1" src="https://user-images.githubusercontent.com/16888757/41483113-1eaad448-70d8-11e8-8476-cb088b3d05eb.png">
<img width="590" alt="dx-pdb2" src="https://user-images.githubusercontent.com/16888757/41483114-1ecee9c8-70d8-11e8-900d-60a7bff5b1ee.png">

**Comment by arnoldnipper** [comment]
@job do you mind to file a feature request in /peeringdb then

**Comment by job** [comment]
Sure. Let’s close this one out. “Works as designed”.

(Btw, very creative idea! :-))

**Comment by vegu** [comment]
@job 's assessment is correct. It currently is not allowed to include third-party hosted images in the notes markdown. The fact that the editor shows it working during the edit process is a bug and should be fixed as it gives the impression that it should work, when in reality it does not.
