### ISSUE TITLE
Improve spam blocking

### ISSUE THREAD

**Issue by job** [peeringdb/admincom#2]
Currently there are between 5 and 10 spam messages that make it into the Deskpro system. Someone should check whether google can do some pre-filtering for the obvious crap.

**Comment by arnoldnipper** [comment]
Any progress, @job ?

**Comment by job** [comment]
I don't see an easy way to do this, without risking to nuke legit email as well. I think we should accept the current status as closing spam is easy compared to missing legit emails & subsequently poorly serving the endusers

**Comment by arnoldnipper** [comment]
Fully agree ... spam is easy to identify and to get rid of.
