### ISSUE TITLE
De-board Brad Raymo from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#200]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[x] remove from admin page in PDB deck
[ ] award plaque sent, 09/2017 - 08/2018

10826 W Saddlehorn Rd
Peoria, AZ 85383

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by job** [comment]
[x] remove from admincom mailing list

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent, 09/2017 - 08/2018

10826 W Saddlehorn Rd
Peoria, AZ 85383

*: Suspended, G-Suite deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent, 09/2017 - 08/2018
