### ISSUE TITLE
De-board Bryan Jong from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#201]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[x] remove from admin page in PDB deck
[ ] award plaque sent

07/2017 - 08/2018

8451 SW Pointer Way Apt J
Portland, OR 97225

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by job** [comment]
[x] remove from admincom mailing list

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

07/2017 - 08/2018

8451 SW Pointer Way Apt J
Portland, OR 97225

*: Suspended, G-Suite deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent
