### ISSUE TITLE
De-board Rob Parker from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#202]
[x] deskpro
[x] downgrade peeringdb user
[ ] remove from admincom mailing list
[x] remove from admin page in PDB deck
[ ] award plaque sent

11/2017 - 08/2018

Seckbacher Landstraße 74
60389 Frankfurt am Main
Germany

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by job** [comment]
[x] remove from admincom mailing list

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[wasn't on list as of 2019-04-12] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

11/2017 - 08/2018

Seckbacher Landstraße 74
60389 Frankfurt am Main
Germany

*: Suspended, G-Suite deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent
