### ISSUE TITLE
make maillog accessible to admincomm (at least nipper)

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#21]
(www.peeringdb.com:log 409 )ls -l maillog
-rw-r-x---+ 1 root root 838909 May  3 19:59 maillog

(www.peeringdb.com:log 410 )id
uid=1025(nipper) gid=1025(nipper) groups=1025(nipper),994(nginx) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

Reason: every know and then we need to lookup whether we received / sent an email

**Comment by job** [comment]
you should be able to access the maillog

```
[root@www ~]# usermod -a -G pdb_admins nipper
[root@www ~]# groups nipper
nipper : nipper nginx pdb_admins
[root@www ~]#
```

**Comment by job** [comment]
```
[root@www ~]# su nipper
(www.peeringdb.com:root 403 ) tail -n 1 /var/log/maillog
May  3 16:50:02 www postfix/qmgr[15786]: 151265C19D6: removed
(www.peeringdb.com:root 404 )
```

**Comment by arnoldnipper** [comment]
Thanks, Job ... will that also survive a reboot / fresh installation?

**Comment by job** [comment]
On Wed, May 03, 2017 at 02:32:14PM -0700, Arnold Nipper wrote:
> Thanks, Job ... will that also survive a reboot / fresh installation? 

I'm taking that up with 20c, it should! :-)

**Comment by arnoldnipper** [comment]
iirc my permissions to access nginx logs were lost after Matt re-installed the vm as he forgot to configure this in the provisioning system as well.

**Comment by grizz** [comment]
@arnoldnipper not sure how, I just double checked and you're in the nginx group

**Comment by arnoldnipper** [comment]
read carefully, Matt :)

**Comment by grizz** [comment]
You're in the nginx group in ansible and on the machine, shrug

**Comment by arnoldnipper** [comment]
And I guess I should be in the pdb_admins group in ansible as well ;-) ... got it?

**Comment by grizz** [comment]
@job already did it :)
