### ISSUE TITLE
Why does that entry get removed?

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#212]
https://peeringdb.com/cp/peeringdb_server/ixlanixfmemberimportlog/450/change/ -> ASN 204345

Customer and I have added the entry according to https://manager.kleyrex.net/api/v4/member-export/ixf/0.7, but it gets removed every night. A more verbose reason why it gets deleted would help a lot.

**Comment by grizz** [comment]
peeringdb/peeringdb#376 fixes this -- please don't assign us to admincom issues

I think it's safe to close, but up to you.
