### ISSUE TITLE
Difference between RDAP and Whois? Here ASN 132068

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#220]
Please see https://peeringdb.com/cp/peeringdb_server/deskproticket/6120/change/

The tool created objects while whois says that this ASN is not assigned

whois -h whois.apnic.net -T aut-num AS132068
% [whois.apnic.net]
% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

%ERROR:101: no entries found
%
% No entries found in source APNIC,JPNIC,KRNIC,TWNIC,IDNIC.

% This query was served by the APNIC Whois Service version 1.88.15-46 (WHOIS-UK3)

**Comment by netravnen** [comment]
RDAP: succes
WHOIS: fail
**Issue on APNIC's side?**
```
$ curl -sG http://rdap.apnic.net/autnum/132068 | jq '.name, .handle, .remarks'
"DIGICORE-HK"
"AS132068"
[
  {
    "description": [
      "DIGICORE LIMITED",
      "9B, AMTEL BUILDING, 148 DES VOEUX ROAD CENTRAL, CENTRAL",
      "http://www.digicoreglobal.com"
    ],
    "title": "description"
  },
  {
    "description": [
      "For any info on hacking, spamming & abuse complaints email",
      "abuse@digicoreglobal.com"
    ],
    "title": "remarks"
  }
]
```

**Comment by arnoldnipper** [comment]
I've contacted APNIC
