### ISSUE TITLE
Add Stefan Funke as PeeringDB Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#227]
[ ] gmail stefan@peeringdb.com (Stefan Funke <stefan@stadtaffe.eu>)
[ ] slack
[ ] deskpro
[ ] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by arnoldnipper** [comment]
[ ] gmail (Stefan Funke stefan@stadtaffe.eu)
[ ] slack
[ ] deskpro
[x] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by arnoldnipper** [comment]
[ ] gmail stefan@peeringdb.com (Stefan Funke stefan@stadtaffe.eu)
[ ] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ccaputo** [comment]
[x] gmail stefan@peeringdb.com (Stefan Funke stefan@stadtaffe.eu)
[ ] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ccaputo** [comment]
[x] gmail stefan@peeringdb.com (Stefan Funke stefan@stadtaffe.eu)
[ ] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by arnoldnipper** [comment]
[x] gmail stefan@peeringdb.com (Stefan Funke stefan@stadtaffe.eu)
[x] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ghankins** [comment]
[x] gmail stefan@peeringdb.com (Stefan Funke stefan@stadtaffe.eu)
[x] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[x] add to admin page in PDB deck, i.e. e-mail Greg
