### ISSUE TITLE
Add Julimar as admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#23]
[x] gmail
[x] slack
[x] deskpro
[x] upgraded peeringdb user to admin
[x] add to admincom mailing list
[ ] add to admin page in PDB deck

**Comment by job** [comment]
[x] gmail

**Comment by job** [comment]
[x] slack

**Comment by job** [comment]
[x] add to admincom mailing list

**Comment by job** [comment]
[x] deskpro

**Comment by job** [comment]
I forwarded the photo and name to @ghankins

**Comment by ghankins** [comment]
[X] add to admin page in PDB deck
