### ISSUE TITLE
De-board Marty Strong from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#231]
[x] deskpro
[x] downgrade peeringdb user
[ ] remove from admincom mailing list
[ ] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

11/2017 - 12/2018

1 Rathbone Square
London
W1T 1FB
United Kingdom

**Comment by ghankins** [comment]
[s] remove from admin page in PDB deck

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

11/2017 - 12/2018

1 Rathbone Square
London
W1T 1FB
United Kingdom

 *: Suspended, G-Suite deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent
