### ISSUE TITLE
De-board Noelle Kenny from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#235]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from admincom mailing list
- [x] close peeringdb.com email address
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] reassign github issues
- [x] remove from peeringdb github team

Term 11/2017 - 01/2019

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

Term 11/2017 - 01/2019

2217 15th Street
San Francisco, CA, 94114.

*: Suspended, G-Suite deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by ccaputo** [comment]
Aaron is working on this.

**Comment by arnoldnipper** [comment]
@ccaputo , did Aaron finish this issue?

**Comment by ccaputo** [comment]
I don't know, but I have re-asked him.

**Comment by ghankins** [comment]
Can someone please check on these:
reassign github issues
remove from peeringdb github team

**Comment by ccaputo** [comment]
[&] reassign github issues
[x] remove from peeringdb github team

&: Didn't notice any on https://github.com/peeringdb/peeringdb/issues
