### ISSUE TITLE
De-board Sean Donovan from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#236]
[ ] deskpro
[ ] downgrade peeringdb user
[ ] remove from admincom mailing list
[ ] close peeringdb.com email address
[x] remove from admin page in PDB deck
[ ] award plaque sent

Term 07/2018 - 01/2019

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by arnoldnipper** [comment]
[x] award plaque sent resp. will not be sent as Sean was on board only for a couple of weeks

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[Suspended, deletion scheduled for 1 month from today] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent resp. will not be sent as Sean was on board only for a couple of weeks

**Comment by ccaputo** [comment]
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[*] close peeringdb.com email address
[x] remove from admin page in PDB deck
[x] award plaque sent resp. will not be sent as Sean was on board only for a couple of weeks

*: Suspended, G-Suite deletion scheduled for 1 month from today on Caputo's calendar.  Feel free to close this ticket.
