### ISSUE TITLE
Unboard Eduardo

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#24]
[x] gmail
[x] slack
[x] deskpro
[x] downgraded peeringdb user
[x] remove from admincom mailing list
[x] remove admin page in PDB deck

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgraded peeringdb user

**Comment by ghankins** [comment]
[X] remove admin page in PDB deck (done with the new update a few weeks ago)

**Comment by job** [comment]
[x] gmail
[x] slack
[x] remove from admincom mailing list

**Comment by arnoldnipper** [comment]
[ ] award plaque sent
