### ISSUE TITLE
De-board Hendrik Braasch from AC

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/admincom#241]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from admincom mailing list
- [x] close peeringdb.com email address
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] reassign github issues
- [x] remove from peeringdb github team

Term 2/2017 - 11/2019   (Start date determined from Arnold welcome email on 2017-02-20.)

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck
[x] remove from admin page on docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] remove from admincom mailing list
[x] close peeringdb.com email address (suspended 2019-11-15, docketed by Caputo to be closed in 30 days)

**Comment by ccaputo** [comment]
Marking these as done since I don't see Hendrik on GitHub:
[x] reassign github issues
[x] remove from peeringdb github team

**Comment by arnoldnipper** [comment]
[x] deskpro
