### ISSUE TITLE
Creating new ix record via API

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#244]
For the task of dropping IX lans I'm writing a script. The idea is to create for each additional ixlan a new IX with the properties (org, contact, local facilities) of the existing IX. However, when trying to create a new IX I already fail. And the error message simply does not reveal the reason why.

I call "curl -snG https://tutorial.peeringdb.com/api/ix -H "Accept: application/json" -X POST -d @$TMP1". Input and output files are attached. 

Any ideas what is going wrong? Next question: for changing the ixkan and netixlan records may I simply use PUT and change ix_id and ixlan_id?
[copy_ix-13566-1.txt](https://github.com/peeringdb/admincom/files/3943160/copy_ix-13566-1.txt)
[copy_ix-13566-2.txt](https://github.com/peeringdb/admincom/files/3943161/copy_ix-13566-2.txt)

**Comment by arnoldnipper** [comment]
@peeringdb/pc , please support as AC needs this script to help customers get rid of the multiple `ixlan` setup.

**Comment by shane-kerr** [comment]
I don't know about the specific issue but I'm willing to support a related issue to fix problem of the error returned being basically unusable:
```json
  "meta": {
    "error": "Unknown"
  }
```

**Comment by arnoldnipper** [comment]
PEBCAK error

**Comment by grizz** [comment]
@shane-kerr agree, I created an issue. 

> PEBCAK error


If there was better error reporting for missing data, the PEBCAK typo would have never turned into an issue as I'm sure you would have realized what the problem was and corrected it.

**Comment by arnoldnipper** [comment]
Indeed: always look on the bright side of life 💃
