### ISSUE TITLE
Insert links into ID fields in AUTOASN tickets

### ISSUE THREAD

**Issue by netravnen** [peeringdb/admincom#245]
Can I request we add Links to peeringdb.com to ID fields in e.g. AUTOASN ticket created in Deskpro?

![image](https://user-images.githubusercontent.com/1938389/71623148-d3882000-2bda-11ea-8d57-28ada856c1a0.png)

**Comment by netravnen** [comment]
@vegu @grizz ?
Commentary input requested, if possible.

**Comment by arnoldnipper** [comment]
Please reopen in peeringdb. Admincom queue is for admincom only issues
