### ISSUE TITLE
Add Alexandre Guimaraes as PeeringDB Admin

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/admincom#249]
[x] gmail alexandre@peeringdb.com (see internal stewards mail for personal e-mail address)
[x] slack
[ ] deskpro
[ ] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[x] add to admin page in PDB deck, i.e. e-mail Greg
[x] add to admin page on docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] gmail alexandre@peeringdb.com (see internal stewards mail for personal e-mail address)
[ ] slack
[ ] deskpro
[ ] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg
[x] add to admin page on docs.peeringdb.com

**Comment by ghankins** [comment]
[x] slack

**Comment by job** [comment]
What is Alexandre's peeringdb user name?

Is the only other thing left to create a deskpro account?

**Comment by funkestefan** [comment]
[x] gmail alexandre@peeringdb.com (see internal stewards mail for personal e-mail address)
[x] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[x] add to admin page in PDB deck, i.e. e-mail Greg
[x] add to admin page on docs.peeringdb.com
