### ISSUE TITLE
Add Shaun Coffey as PeeringDB Admin

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/admincom#250]
[x] gmail shaun@peeringdb.com (see internal stewards mail for personal e-mail address)
[x] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[x] add to admin page in PDB deck, i.e. e-mail Greg
[x] add to admin page on docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] gmail shaun@peeringdb.com (see internal stewards mail for personal e-mail address)
[ ] slack
[ ] deskpro
[ ] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by funkestefan** [comment]
[x] gmail shaun@peeringdb.com (see internal stewards mail for personal e-mail address)
[ ] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg
[x] add to admin page on docs.peeringdb.com

**Comment by ghankins** [comment]
[x] slack

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg
