### ISSUE TITLE
Data Ownership TF recommendation - AdminComm dispute resolution procedure

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/admincom#251]
Per [PeeringDB Data Ownership Policy Document](https://docs.peeringdb.com/gov/misc/2020-04-06_PeeringDB_Data_Ownership_Policy_Document_v1.0.pdf) the Task Force has recommended the following:

```
3.3) Admin Committee
[...]
This Task Force recommends that the Admin Committee charter be amended to include a general
dispute resolution procedure that covers data ownership in addition to other potential disputes.
```

**Comment by ccaputo** [comment]
Based on discussions, my understanding is that the Board is expected to require the dispute resolution procedure include a process of appeal of decisions to the PeeringDB Board.

**Comment by funkestefan** [comment]
I will think about the TF recommendations and the requirements over the next days.

**Comment by ccaputo** [comment]
Harmonized language used by the committees is coming soon.
