### ISSUE TITLE
Add Gaël Hernandez as PeeringDB Admin

### ISSUE THREAD

**Issue by ghankins** [peeringdb/admincom#252]
- [x] gmail [gael@peeringdb.com](mailto:gael@peeringdb.com) (see internal stewards mail for personal e-mail address)
- [x] slack
- [x] deskpro
- [x] create / upgrade peeringdb user to admin
- [x] add to admincom mailing list
- [x] add to admin page in PDB deck, i.e. e-mail Greg
- [x] add to admin page on docs.peeringdb.com

**Comment by ghankins** [comment]
[x] add to admin page on docs.peeringdb.com

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ccaputo** [comment]
- [x] gmail [gael@peeringdb.com](mailto:gael@peeringdb.com)
- [x] add to admincom mailing list

**Comment by arnoldnipper** [comment]
I've done the resr
