### ISSUE TITLE
De-board Darwin Da Costa from AC

### ISSUE THREAD

**Issue by ghankins** [peeringdb/admincom#253]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from admincom mailing list
- [x] close peeringdb.com email address
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] reassign github issues
- [x] remove from peeringdb github team

Term 01/2020 - 01/2023

**Comment by ghankins** [comment]
- [x] remove from Slack
- [x] remove from admincom mailing list
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com

**Comment by ccaputo** [comment]
[x] downgrade peeringdb user
[*] close peeringdb.com email address
[&] reassign github issues
[x] remove from peeringdb github team

*: Suspended, Google Workspace deletion scheduled for 1 month from today on Caputo's calendar.
&: Didn't notice any on https://github.com/peeringdb/peeringdb/issues

**Comment by arnoldnipper** [comment]
- [x] deskpro
