### ISSUE TITLE
De-board Stefan Funke from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#254]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] remove from admincom mailing list
- [x] close peeringdb.com email address
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] reassign github issues
- [x] remove from peeringdb github team

Term 11/2018 - 11/2023

**Comment by arnoldnipper** [comment]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from Slack
- [x] reassign github issues

**Comment by arnoldnipper** [comment]
@ghankins and @ccaputo, please work on the other items

**Comment by ccaputo** [comment]
[x] remove from admincom mailing list - Was already done as of 20230118 0228 UTC.
[*] close peeringdb.com email address
[x] remove from peeringdb github team

*: Suspended, Google Workspace deletion scheduled for 1 month from today on Caputo's calendar.

**Comment by ghankins** [comment]
- [ ] remove from admin page in PDB deck
- [ ] remove from admin page on docs.peeringdb.com
