### ISSUE TITLE
Onboard Elizabeth Culley

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#255]
- [x] gmail [elizabeth@peeringdb.com](mailto:elizabeth@peeringdb.com) (see internal stewards mail for personal email address)
- [x] slack
- [x] deskpro
- [x] create / upgrade peeringdb user to admin
- [x] check for 2FA
- [x] add to admincom mailing list
- [ ] add to admin page in PDB deck, i.e. email Greg
- [x] add to admin page on docs.peeringdb.com
- [ ] add to AC GitHub team (username needed first, what is it?)

**Comment by ghankins** [comment]
- [x] slack
- [x] add to admin page on docs.peeringdb.com

**Comment by arnoldnipper** [comment]
- [x] deskpro

**Comment by netravnen** [comment]
@ccaputo can you resend the password to Elizabeth? `Elizabeth_Culley@comcast.com`

**Comment by ccaputo** [comment]
> @ccaputo can you resend the peeringdb google password to Elizabeth?

Done.

**Comment by netravnen** [comment]
@ccaputo Can you add Elizabeth to the Peering GitHub organization? Username `LizCulley`

**Comment by ccaputo** [comment]
> @ccaputo Can you add Elizabeth to the Peering GitHub organization? Username `LizCulley`

Sure thing. Now invited.

**Comment by netravnen** [comment]
**TO BE DE-BOARDED**

**Comment by ghankins** [comment]
Opening a new issue for deboard.
