### ISSUE TITLE
Onboard Ron Grant 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#256]
- [x] gmail [ron@peeringdb.com](mailto:ron@peeringdb.com) (see internal stewards mail for personal email address)
- [x] slack
- [x] deskpro
- [x] create / upgrade peeringdb user to admin
- [x] check for 2FA
- [x] add to admincom mailing list
- [x] add to admin page in PDB deck, i.e. email Greg
- [x] add to admin page on docs.peeringdb.com
- [x] add to AC GitHub team (username needed first, what is it?)

**Comment by ghankins** [comment]
- [x] slack
- [x] add to admin page on docs.peeringdb.com

**Comment by arnoldnipper** [comment]
- [x] deskpro

**Comment by arnoldnipper** [comment]
- [x] create / upgrade peeringdb user to admin

**Comment by ghankins** [comment]
- [x] add to admin page in PDB deck, i.e. email Greg

**Comment by netravnen** [comment]
- [x] github, https://github.com/rgrant
