### ISSUE TITLE
Onboard Faisal Reza

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#259]
- [x] gmail [faisal@peeringdb.com](mailto:faisal@peeringdb.com) (see internal mail for personal email address)
- [x] slack
- [x] deskpro
- [ ] create / upgrade peeringdb user to admin
- [ ] check for 2FA
- [x] add to admincom mailing list
- [ ] add to admin page in PDB deck, i.e. email Greg
- [x] add to admin page on docs.peeringdb.com
- [ ] add to AC GitHub team (username needed first, what is it?)

**Comment by ghankins** [comment]
- [x] slack
- [x] add to admin page on docs.peeringdb.com

**Comment by arnoldnipper** [comment]
- [x] deskpro

**Comment by netravnen** [comment]
**TO BE DE-BOARDED**

**Comment by ghankins** [comment]
Opening a new issue for deboard.

**Comment by ghankins** [comment]
Opening a new issue for deboard.

**Comment by ghankins** [comment]
Opening a new issue for deboard.

**Comment by ghankins** [comment]
Opening a new issue for deboard.
