### ISSUE TITLE
De-board Arnold Nipper from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#261]
- [x] deskpro
- [x] downgrade peeringdb user to staff
- [x] remove from admincom mailing list
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com

**Comment by ghankins** [comment]
- [x] remove from admincom mailing list: someone already did this
- [ ] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com

**Comment by netravnen** [comment]
- [x] remove personal API key from deskpro
