### ISSUE TITLE
Deboard Patrick Gilmore from AC

### ISSUE THREAD

**Issue by ghankins** [peeringdb/admincom#264]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from admincom mailing list
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] remove from peeringdb AC github team

Patrick would like to keep his email address and Slack access.

**Comment by ccaputo** [comment]
- [x] downgrade peeringdb user - Wasn't needed to be done since he wasn't a superuser.
- [x] remove from admincom mailing list
- [x] remove from peeringdb AC github team - Wasn't on the AC github team.

**Comment by ghankins** [comment]
- [x] remove from admin page on docs.peeringdb.com

**Comment by netravnen** [comment]
- [x] deskpro

**Comment by ghankins** [comment]
- [ ] remove from admin page in PDB deck
