### ISSUE TITLE
Update AC team

### ISSUE THREAD

**Issue by netravnen** [peeringdb/admincom#265]
After the recent election for the Chair and Vice-Chair of the AC. We should probably update the maintainer for the AC team, https://github.com/orgs/peeringdb/teams/ac

- [x] Deboard the old-old-chair /Arnold/ as the maintainer of the team
- [x] Onboard the recently elected chair /CHriztoffer/ as the maintainer of the team

**Comment by ghankins** [comment]
I don't have administrative privileges for GitHub.

**Comment by ccaputo** [comment]
Done.
