### ISSUE TITLE
Onboard Ankesh Anand PDB

### ISSUE THREAD

**Issue by netravnen** [peeringdb/admincom#269]
- [x] gmail `ankesh@peeringdb.com` (see internal mail for personal email address)
- [x] slack
- [x] deskpro
- [x] create / upgrade peeringdb user to admin
- [x] check for 2FA
- [x] add to admincom mailing list
- [x] add to admin page in PDB deck, i.e. email Greg
- [x] add to admin page on docs.peeringdb.com
- [x] add to AC GitHub team (username needed first, what is it?),

**Comment by ccaputo** [comment]
- [x] gmail `ankesh@peeringdb.com` (see internal mail for personal email address)
- [x] add to admincom mailing list

**Comment by netravnen** [comment]
Github `ankeshanand1`

**Comment by ghankins** [comment]
- [ ] slack
- [ ] add to admin page in PDB deck, email sent
- [ ] add to admin page on docs.peeringdb.com

**Comment by netravnen** [comment]
[x] create / upgrade peeringdb user to admin

**Comment by ghankins** [comment]
- [x] add to admin page in PDB deck
