### ISSUE TITLE
Deboard Tom Samplonius

### ISSUE THREAD

**Issue by ghankins** [peeringdb/admincom#275]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from admincom mailing list
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] remove from peeringdb AC github team
- [x] remove personal API key from deskpro
- [x] remove from Slack

**Comment by ghankins** [comment]
- [x] remove from Slack

**Comment by ghankins** [comment]
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com

**Comment by cappaxyz** [comment]
> * [X]  deskpro
> * [X]  remove personal API key from deskpro

Removed from Deskpro previously, safe to close.
