### ISSUE TITLE
Deboard Faisal Reza

### ISSUE THREAD

**Issue by ghankins** [peeringdb/admincom#276]
- [x] deskpro
- [x] downgrade peeringdb user
- [x] remove from admincom mailing list
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] remove from peeringdb AC github team
- [x] remove personal API key from deskpro
- [x] remove from Slack

**Comment by ghankins** [comment]
- [x] remove from Slack

**Comment by ghankins** [comment]
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com

**Comment by cappaxyz** [comment]
> * [X]  deskpro
> * [X]  remove personal API key from deskpro

Removed from Deskpro previously, safe to close.

**Comment by ccaputo** [comment]
Was missing this in the above checklist, but I have now done it since no recent sign-in:

- [x] close peeringdb.com email address
