### ISSUE TITLE
Deboard Ryan Williams

### ISSUE THREAD

**Issue by ghankins** [peeringdb/admincom#277]
- [ ] deskpro
- [x] downgrade peeringdb user
- [x] remove from admincom mailing list
- [x] remove from admin page in PDB deck
- [x] remove from admin page on docs.peeringdb.com
- [x] remove from peeringdb AC github team
- [ ] remove personal API key from deskpro
- [x] remove from Slack

**Comment by ghankins** [comment]
- [ ] remove from Slack

**Comment by ccaputo** [comment]
- [x] remove from admincom mailing list
- [x] remove from peeringdb AC github team (wasn't actually there)

**Comment by cappaxyz** [comment]
> * [X]  deskpro
> * [X]  remove personal API key from deskpro

Deskpro items completed previously, safe to close

**Comment by ccaputo** [comment]
Was missing this in the above checklist, but I have now done it since no recent sign-in:

- [x] close peeringdb.com email address
