### ISSUE TITLE
Add Luisa Fernanda Villa y Battenberg <fernandavilla@gmail.com> as Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#29]
[x] gmail
[x] slack
[x] deskpro
[] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[x] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
[x] gmail
[x] slack
[x] deskpro
[] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
@arnoldnipper what is the peeringdb username to be upgraded? People should always create their own account, we should merely upgrade when they become admin.

@ghankins can you fix the deck?

**Comment by arnoldnipper** [comment]
@job Luisa does not yet have an account. I'll tell here to create one and upgrade her

**Comment by ghankins** [comment]
Asked Luisa for photo Tue, 13 Jun 2017 23:40:11 -0400.

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg
