### ISSUE TITLE
Autorespond to users with DeskPRO ticketnumber

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#3]
Currently users only get a confirmation e-mail w/o any ticket number resp. the reference is hidden in the e-mail header.

A ticket number to refer to would be nice

**Comment by job** [comment]
full agree

**Comment by job** [comment]
I'd prefer if the ticket number is embedded somewhere in the `Subject:` line of the email

**Comment by arnoldnipper** [comment]
I've done two configs:

 1. Tickets ID now are YYYY-MM-nnnn

 2. Ticket ID is now added to the auto-reply

**Comment by arnoldnipper** [comment]
Ticket ID is "PDB #nnnnnnnn"
