### ISSUE TITLE
Add Bryan Jong <bryan@bryanjong.co> as Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#30]
[x] gmail
[x] slack
[x] deskpro
[x] create / upgrade peeringdb user to admin
[x] add to admincom mailing list
[x] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
[x] gmail
[x] slack
[x] deskpro
[x] upgrade user
[x] admincom

**Comment by job** [comment]
@ghankins final task is with you

**Comment by ghankins** [comment]
Asked Bryan for photo Wed, 14 Jun 2017 09:34:28 -0400.

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg
