### ISSUE TITLE
Organization No matches found (17408) was automatically created during user 'interdominios's affiliation request to AS48348

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#35]
"No matches found" is probably not an organisation (https://peeringdb.com/org/17408)

My script gives

 org-name:       Cloud Builders SA

**Comment by arnoldnipper** [comment]
See also DeskPRO https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:7105,vis:6

**Comment by vegu** [comment]
Odd, that does sound like a bug, trying to reproduce at the moment, will update when i know more.

**Comment by arnoldnipper** [comment]
same again here: https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7199,vis:6

**Comment by vegu** [comment]
Created a ticket for this on the main board: https://github.com/peeringdb/peeringdb/issues/185
