### ISSUE TITLE
Autocreation tool picks wrong organisation

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#37]
DeskPRO https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7141,vis:6

ASN 205697
Org according spec: Informatica y Comunicacion Salamanca S.L.U <-- org-name
org picked: ALOJALIA-AS <-- as-name

**Comment by arnoldnipper** [comment]
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,p:4783,t.o:7349,vis:6

ASN 206050
Org according spec: FreeNetwork s.r.o. <-- org-name
Org picked: AS206050 <-- aut-num ???

**Comment by arnoldnipper** [comment]
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7240,vis:6

ASN 61399
Org according spec: KG-IX LLC <- org-name
Org picked: AS61399 <-- aut-num ???

**Comment by arnoldnipper** [comment]
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7211,vis:6

ASN 49037
Org according spec: Megalink Ltd <-- org-name
Org picked: AS49037 <-- aut-num ???

**Comment by grizz** [comment]
Issue moved to [peeringdb/peeringdb #186](https://github.com/peeringdb/peeringdb/issues/186) via [**ZenHub**](https://www.zenhub.com/)

**Comment by arnoldnipper** [comment]
Looks like rdap info sucks :(
