### ISSUE TITLE
duplicate tickets opened for user approval

### ISSUE THREAD

**Issue by grizz** [peeringdb/admincom#4]
@grizz commented on [Thu Nov 17 2016](https://github.com/peeringdb/peeringdb/issues/81)

---

@grizz commented on [Thu Dec 01 2016](https://github.com/peeringdb/peeringdb/issues/81#issuecomment-264327499)

Looks like a failure on deskpro to combine tickets with the same subject (resulting from separate user requests).

@arnoldnipper has a ticket open with Deskpro

---

@job commented on [Wed Dec 07 2016](https://github.com/peeringdb/peeringdb/issues/81#issuecomment-265598580)

this can move to https://github.com/peeringdb/admincom/issues

**Comment by arnoldnipper** [comment]
Hopefully solved by enabling here: https://peeringdb.deskpro.com/agent/#admin:/tickets/ticket_accounts/advanced-settings
