### ISSUE TITLE
Remove Eric Lindsjö as admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#48]
[x] gmail
[x] slack
[x] still in # general
[x] deskpro
[x] downgrade peeringdb user
[x] remove from admincom mailing list
[x] remove from admin page in PDB deck
[ ] award plaque sent

**Comment by job** [comment]
[x] slack
[x] gmail
[x] admincom mailing list

**Comment by ghankins** [comment]
[X] remove from admin page in PDB deck

**Comment by arnoldnipper** [comment]
[ ] award plaque sent
