### ISSUE TITLE
Add Brad Rymo (brad.raymo@gmail.com) as PeeringDB Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#52]
[ ] gmail
[ ] slack
[x] deskpro: brad.raymo@peeringdb.com
    [ ] turn on email notification
[x] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
[x] gmail - brad@peeringdb.com
[x] slack
[x] admincom

**Comment by arnoldnipper** [comment]
[x] turn on email notification

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by arnoldnipper** [comment]
@job I don't see Brad on slack ...

**Comment by job** [comment]
I did invite him, he may need to click the invitation link?

**Comment by arnoldnipper** [comment]
Doooh :)
