### ISSUE TITLE
Add Bijal Sanghani (bijal@euro-ix.net) as PeeringDB admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#53]
[ ] gmail: bijal@peeringdb.com
[ ] slack
[ ] deskpro
[ ] turn on email notification
[ ] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by arnoldnipper** [comment]
[x] create / upgrade peeringdb user to admin

**Comment by job** [comment]
[x] slack ("This person is already in the workspace")
[x] deskpro
[x] admincom (bijal @ euroix is subscribed)

**Comment by job** [comment]
[x] gmail: bijal@peeringdb.com

**Comment by ghankins** [comment]
I think Arnold did this:
[x] add to admin page in PDB deck, i.e. e-mail Greg
