### ISSUE TITLE
Remove Florian Hibler as Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#55]
[ ] gmail
[ ] slack
[ ] deskpro
[ ] downgrade peeringdb user
[ ] remove from admincom mailing list
[ ] remove from admin page in PDB deck
[ ] award plaque sent

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by job** [comment]
[x] gmail / admincom mailing list / slack / deskpro

**Comment by arnoldnipper** [comment]
[x] downgrade peeringdb user
[ ] award plaque sent

**Comment by arnoldnipper** [comment]
[x] award plaque sent
