### ISSUE TITLE
Remove Michael Still as Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#56]
[ ] gmail
[ ] slack
[ ] deskpro
[ ] downgrade peeringdb user
[ ] remove from admincom mailing list
[ ] remove from admin page in PDB deck
[ ] award plaque sent

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by job** [comment]
[x] gmail / slack / deskpro / admincom mailing list

**Comment by arnoldnipper** [comment]
[x] downgrade peeringdb user
[ ] award plaque sent

**Comment by arnoldnipper** [comment]
[x] award plaque sent
