### ISSUE TITLE
Add Noelle Kenny ad PeeringDB Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#58]
[ ] gmail (Noelle Kenny <noelle@inflect.com>)
[ ] slack
[ ] deskpro
[ ] turn on email notification
[ ] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[ ] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ghankins** [comment]
[x] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
[x] gmail
[x] slack
[x] deskpro
[x] admincom mailing list

**Comment by arnoldnipper** [comment]
[ ] create / upgrade peeringdb user to admin
