### ISSUE TITLE
Add Rob Parker as PeeringDB Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#60]
[ ] gmail (Rob Parker <rob@wasteground.net>)
[ ] slack
[ ] deskpro
[ ] turn on email notification
[ ] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[X] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ghankins** [comment]
[X] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
[x] gmail
[x] deskpro
[x] slack
[x] admincom mailinglist

**Comment by arnoldnipper** [comment]
[x] create / upgrade peeringdb user to admin
