### ISSUE TITLE
Add Marty Strong as PeeringDB Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#61]
[ ] gmail (Marty Strong <marty@cloudflare.com>)
[ ] slack
[ ] deskpro
[ ] turn on email notification
[ ] create / upgrade peeringdb user to admin
[ ] add to admincom mailing list
[X] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by ghankins** [comment]
[X] add to admin page in PDB deck, i.e. e-mail Greg

**Comment by job** [comment]
[x] gmail
[x] deskpro
[x] slack
[x] admincom mailinglist

**Comment by arnoldnipper** [comment]
[x] create / upgrade peeringdb user to admin
