### ISSUE TITLE
It's possible to enter the same IP address twice (duplicate IP addresses)

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#62]
It's still 
![20171115 peeringdb 00](https://user-images.githubusercontent.com/16888757/32837154-bba1af74-ca0c-11e7-830a-055a2033d81d.png)
possible to enter the same IP address twice (duplicate IP addresses)

**Comment by job** [comment]
closed?

**Comment by arnoldnipper** [comment]
yes and re-opened an issue in peeringdb
