### ISSUE TITLE
Look into DeskPRO#11769

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#64]
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:11769

**Comment by arnoldnipper** [comment]
![image001](https://user-images.githubusercontent.com/16888757/33401514-d730707e-d559-11e7-8771-1fbf2a56dbfc.png)
Customer says:
Hi Nipper,
There issue existed for a period of time , we capture some info below this. Pls check it ,thanks a lot.
 
When our customers register account , but the web has no responded, you can see the capture of register process.
 
![303632747792160822](https://user-images.githubusercontent.com/16888757/33401497-cdf205e0-d559-11e7-8ee2-ee9c30418dfd.png)

**Comment by vegu** [comment]
Seeing as this report is from China, i still think this might be part of the re-captcha issue described in https://github.com/peeringdb/peeringdb/issues/38 - as the recaptcha form does not even show up in the screenshot pictured above.

**Comment by arnoldnipper** [comment]
Yes, this is the same as https://github.com/peeringdb/peeringdb/issues/38 ... do we have an alternate re-captcha solution?

**Comment by vegu** [comment]
Not at this point, that is what peeringdb/peeringdb#38 addresses.

**Comment by arnoldnipper** [comment]
see https://github.com/peeringdb/peeringdb/issues/38
