### ISSUE TITLE
Merge facility 3361 > 1177

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/admincom#66]
QTS acquired Dupont fabros site in Piscataway, NJ resulting in duplicate facilities. Please merge:

https://www.peeringdb.com/fac/3361 into 
https://www.peeringdb.com/fac/1177

I've already pushed 1177 under the QTS organization. Thanks!

**Comment by vegu** [comment]
Done, please review on your end.

```
Merging facilities 3361
Merging QTS Piscataway (to be merged) (3361) ..
  - netfac NetworkFacility-netfac22264
  - netfac NetworkFacility-netfac24744
soft deleting QTS Piscataway (to be merged)
```
