### ISSUE TITLE
Merge 2 facilities | make script available

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#7]
I need to merge two facilities.

**Comment by vegu** [comment]
which 2 facilities ?

Also, the script is already available if you have access to the pdb box.  Not sure where to put instructions at this point though.

**Comment by arnoldnipper** [comment]
I have ssh access to peerindb.com. Instructions typically are provided via "-h" or "--help"

Facilities to merge are in DeskPRO ticket #1492

**Comment by vegu** [comment]
Usage instructions are already there, but there is the matter of the location of the script as well as python environment activation so you can run it. I will follow up to your email in a minute.

**Comment by job** [comment]
this is regarding merging https://peeringdb.com/fac/332 with https://peeringdb.com/fac/1979

**Comment by job** [comment]
This was done by @vegu . Thanks!
