### ISSUE TITLE
Remove Samer from AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/admincom#73]
[ ] deskpro
[ ] downgrade peeringdb user
[ ] remove from admincom mailing list
[ ] remove from admin page in PDB deck
[ ] award plaque sent

**Comment by arnoldnipper** [comment]
[x] deskpro
[x] downgrade peeringdb user

**Comment by job** [comment]
[x] remove from admincom mailing list

**Comment by ghankins** [comment]
[x] remove from admin page in PDB deck

**Comment by arnoldnipper** [comment]
[x] award plaque sent
