### ISSUE TITLE
Verification queue & lost e-mails

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/admincom#77]
So per the 'lost e-mails' (GitHub issue 280) I was able to clear the pending queue for facilities but we still need to do that for users, networks & IXPs.

A list can be found by looking at the verification queue items from Jan. 19, 2018, 8:08 a.m when the issue started.

It's at https://www.peeringdb.com/cp/peeringdb_server/verificationqueueitem/

The left most column holds a link that lets you inspect each item waiting for verification. Such as https://www.peeringdb.com/cp/peeringdb_server/verificationqueueitem/15500/change/

There you will see both the username that submitted the item, as well as a checkbox labeled 'notified'. If you uncheck that and save you can retrigger the email to DeskPRO (assuming the mailer is fixed).

Otherwise you can use the username to find the email in the user admin to notify them manually.

**Comment by arnoldnipper** [comment]
@peterhelmenstine what do you propose? Tickets stuck in vrfy q may have several reasons. As you seen, we currently have *5k* tickets pending.

**Comment by job** [comment]
On Mon, Jan 29, 2018 at 01:35:15PM -0800, Arnold Nipper wrote:
> @peterhelmenstine what do you propose? Tickets stuck in vrfy q may
> have several reasons. As you seen, we currently have *5k* tickets
> pending.

We don't have 5K things since January 17th do we?

**Comment by peterhelmenstine** [comment]
I was mostly referring to the 50-60 pending items that didn't get Deskpro tickets between Jan 19th to when the fix was implemented on the 24th. I think the Adminco should pound through those. The rest is a whole other issue.

**Comment by arnoldnipper** [comment]
Sounds like a plan. Does that apply to all records? And how to track it? As said. There are tons stuck in the vrfy q. For severaly reasons. Iow: you can't necessartily fix them

**Comment by peterhelmenstine** [comment]
Just submitted a facility and I see it in the queue. No Deskpro ticket or auto e-mail responder. I don't believe this is resolved.

**Comment by arnoldnipper** [comment]
The tool is fine. It simply forgets to check whether the user exists imho
