### ISSUE TITLE
Merge facilities 717, 1244, 73, 842 > 306

### ISSUE THREAD

**Issue by NETRAVNEN** [peeringdb/admincom#79]
Equinix have interconnected the following facility PDB_IDs and want to merge the facilities in the database.

- 717, 1244, 73, 842
- into 306.

https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:14762,vis:6

**Comment by arnoldnipper** [comment]
Log (#842):

Merging facilities 842
Merging Equinix Paris Condorcet (PA6) (formerly TCY Par3) (842) ..
  - netfac NetworkFacility-netfac7268 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac7369
  - netfac NetworkFacility-netfac7706 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac7771 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac8533 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac9821
  - netfac NetworkFacility-netfac10514
  - netfac NetworkFacility-netfac11049
  - netfac NetworkFacility-netfac12319 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac13827 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14340 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac16946
  - netfac NetworkFacility-netfac17768
  - netfac NetworkFacility-netfac18058 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac18103 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac19876
  - netfac NetworkFacility-netfac20068
  - netfac NetworkFacility-netfac21428
  - netfac NetworkFacility-netfac21782 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac21947 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac22068 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac22843
  - netfac NetworkFacility-netfac23531
  - netfac NetworkFacility-netfac26213
  - netfac NetworkFacility-netfac26784 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac27137 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac27232
  - ixfac InternetExchangeFacility-ixfac1283 : connection already exists at target, skipping.
  - ixfac InternetExchangeFacility-ixfac1321
soft deleting InternetExchangeFacility-ixfac1283
soft deleting NetworkFacility-netfac7268
soft deleting NetworkFacility-netfac7706
soft deleting NetworkFacility-netfac7771
soft deleting NetworkFacility-netfac8533
soft deleting NetworkFacility-netfac12319
soft deleting NetworkFacility-netfac13827
soft deleting NetworkFacility-netfac14340
soft deleting NetworkFacility-netfac18058
soft deleting NetworkFacility-netfac18103
soft deleting NetworkFacility-netfac21782
soft deleting NetworkFacility-netfac21947
soft deleting NetworkFacility-netfac22068
soft deleting NetworkFacility-netfac26784
soft deleting NetworkFacility-netfac27137
soft deleting Equinix Paris Condorcet (PA6) (formerly TCY Par3)

Log (#73):

Merging facilities 73
Merging Equinix Paris Victor Hugo (PA5) (formerly TCY Par1) (73) ..
  - netfac NetworkFacility-netfac223
  - netfac NetworkFacility-netfac461 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac946 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac991 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac1383
  - netfac NetworkFacility-netfac1805
  - netfac NetworkFacility-netfac2424
  - netfac NetworkFacility-netfac3407 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac3836 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac5015
  - netfac NetworkFacility-netfac6528 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac8532 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac8544
  - netfac NetworkFacility-netfac9993
  - netfac NetworkFacility-netfac10760
  - netfac NetworkFacility-netfac12318 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac13607 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac13826 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14378 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac15686
  - netfac NetworkFacility-netfac17687
  - netfac NetworkFacility-netfac18057 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac20620 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac23750 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac24022
  - ixfac InternetExchangeFacility-ixfac157
soft deleting NetworkFacility-netfac461
soft deleting NetworkFacility-netfac946
soft deleting NetworkFacility-netfac991
soft deleting NetworkFacility-netfac3407
soft deleting NetworkFacility-netfac3836
soft deleting NetworkFacility-netfac6528
soft deleting NetworkFacility-netfac8532
soft deleting NetworkFacility-netfac12318
soft deleting NetworkFacility-netfac13607
soft deleting NetworkFacility-netfac13826
soft deleting NetworkFacility-netfac14378
soft deleting NetworkFacility-netfac18057
soft deleting NetworkFacility-netfac20620
soft deleting NetworkFacility-netfac23750
soft deleting Equinix Paris Victor Hugo (PA5) (formerly TCY Par1)

Log (#1244):

Merging facilities 1244
Merging Equinix Paris Pantin (PA4) (1244) ..
  - netfac NetworkFacility-netfac547 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac2612 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac3611 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac9909 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac10919 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac11956 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac12323 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac12587
  - netfac NetworkFacility-netfac13829 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac13959 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14333 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14514 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac15739
  - netfac NetworkFacility-netfac17581
  - netfac NetworkFacility-netfac17725
  - netfac NetworkFacility-netfac18056
  - netfac NetworkFacility-netfac13122 (undeleting and updating)
  - netfac NetworkFacility-netfac19732
  - netfac NetworkFacility-netfac20615 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac20771 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac21288 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac22757
  - netfac NetworkFacility-netfac24295
  - netfac NetworkFacility-netfac25171
  - netfac NetworkFacility-netfac27596 : connection already exists at target, skipping.
  - ixfac InternetExchangeFacility-ixfac477 : connection already exists at target, skipping.
soft deleting InternetExchangeFacility-ixfac477
soft deleting NetworkFacility-netfac547
soft deleting NetworkFacility-netfac2612
soft deleting NetworkFacility-netfac3611
soft deleting NetworkFacility-netfac9909
soft deleting NetworkFacility-netfac10919
soft deleting NetworkFacility-netfac11956
soft deleting NetworkFacility-netfac12323
soft deleting NetworkFacility-netfac13829
soft deleting NetworkFacility-netfac13959
soft deleting NetworkFacility-netfac14333
soft deleting NetworkFacility-netfac14514
soft deleting NetworkFacility-netfac19673
soft deleting NetworkFacility-netfac20615
soft deleting NetworkFacility-netfac20771
soft deleting NetworkFacility-netfac21288
soft deleting NetworkFacility-netfac27596
soft deleting Equinix Paris Pantin (PA4)

Log (#717):

Merging facilities 717
Merging Equinix Paris Saint-Denis (PA3)  (717) ..
  - netfac NetworkFacility-netfac1108
  - netfac NetworkFacility-netfac6138 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac6272
  - netfac NetworkFacility-netfac6521 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac6574 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac6895 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac6968
  - netfac NetworkFacility-netfac7084
  - netfac NetworkFacility-netfac8321 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac8495
  - netfac NetworkFacility-netfac8536 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac9290 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac9982
  - netfac NetworkFacility-netfac10222
  - netfac NetworkFacility-netfac10377 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac10539 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac10636
  - netfac NetworkFacility-netfac10644 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac10804 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac10880
  - netfac NetworkFacility-netfac11237
  - netfac NetworkFacility-netfac11685
  - netfac NetworkFacility-netfac11879
  - netfac NetworkFacility-netfac11623 (undeleting and updating)
  - netfac NetworkFacility-netfac13147
  - netfac NetworkFacility-netfac13314
  - netfac NetworkFacility-netfac13533 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac13997 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14334 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14440
  - netfac NetworkFacility-netfac14642
  - netfac NetworkFacility-netfac14678 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14783
  - netfac NetworkFacility-netfac14788 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14805 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac14922
  - netfac NetworkFacility-netfac16142 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac17165
  - netfac NetworkFacility-netfac18898
  - netfac NetworkFacility-netfac18977 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac20008
  - netfac NetworkFacility-netfac20010
  - netfac NetworkFacility-netfac20286 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac20616 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac20753
  - netfac NetworkFacility-netfac21311
  - netfac NetworkFacility-netfac21348 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac21720
  - netfac NetworkFacility-netfac21831 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac21913
  - netfac NetworkFacility-netfac21993
  - netfac NetworkFacility-netfac22208 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac22535 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac22852
  - netfac NetworkFacility-netfac23006
  - netfac NetworkFacility-netfac23008
  - netfac NetworkFacility-netfac24054 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac24731
  - netfac NetworkFacility-netfac26082
  - netfac NetworkFacility-netfac26232 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac26253
  - netfac NetworkFacility-netfac26493 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac26858 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac26934 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac27138 : connection already exists at target, skipping.
  - netfac NetworkFacility-netfac27346
  - ixfac InternetExchangeFacility-ixfac351 : connection already exists at target, skipping.
  - ixfac InternetExchangeFacility-ixfac539 : connection already exists at target, skipping.
  - ixfac InternetExchangeFacility-ixfac1173 : connection already exists at target, skipping.
soft deleting InternetExchangeFacility-ixfac351
soft deleting InternetExchangeFacility-ixfac539
soft deleting InternetExchangeFacility-ixfac1173
soft deleting NetworkFacility-netfac6138
soft deleting NetworkFacility-netfac6521
soft deleting NetworkFacility-netfac6574
soft deleting NetworkFacility-netfac6895
soft deleting NetworkFacility-netfac8321
soft deleting NetworkFacility-netfac8536
soft deleting NetworkFacility-netfac9290
soft deleting NetworkFacility-netfac10377
soft deleting NetworkFacility-netfac10539
soft deleting NetworkFacility-netfac10644
soft deleting NetworkFacility-netfac10804
soft deleting NetworkFacility-netfac11940
soft deleting NetworkFacility-netfac13533
soft deleting NetworkFacility-netfac13997
soft deleting NetworkFacility-netfac14334
soft deleting NetworkFacility-netfac14678
soft deleting NetworkFacility-netfac14788
soft deleting NetworkFacility-netfac14805
soft deleting NetworkFacility-netfac16142
soft deleting NetworkFacility-netfac18977
soft deleting NetworkFacility-netfac20286
soft deleting NetworkFacility-netfac20616
soft deleting NetworkFacility-netfac21348
soft deleting NetworkFacility-netfac21831
soft deleting NetworkFacility-netfac22208
soft deleting NetworkFacility-netfac22535
soft deleting NetworkFacility-netfac24054
soft deleting NetworkFacility-netfac26232
soft deleting NetworkFacility-netfac26493
soft deleting NetworkFacility-netfac26858
soft deleting NetworkFacility-netfac26934
soft deleting NetworkFacility-netfac27138
soft deleting Equinix Paris Saint-Denis (PA3)

**Comment by arnoldnipper** [comment]
Log (#717):

Undeleting facility Equinix Paris Saint-Denis (PA3) (#717)
======================
Undoing merge Equinix Paris Saint-Denis (PA3) (#717)
Undoing network facility merge (#1108)
Undoing network facility merge (#6272)
Undoing network facility merge (#6968)
Undoing network facility merge (#7084)
Undoing network facility merge (#8495)
Undoing network facility merge (#9982)
Undoing network facility merge (#10222)
Undoing network facility merge (#10636)
Undoing network facility merge (#10880)
Undoing network facility merge (#11237)
Undoing network facility merge (#11685)
Undoing network facility merge (#11879)
Undoing network facility merge (#13147)
Undoing network facility merge (#13314)
Undoing network facility merge (#14440)
Undoing network facility merge (#14642)
Undoing network facility merge (#14783)
Undoing network facility merge (#14922)
Undoing network facility merge (#17165)
Undoing network facility merge (#18898)
Undoing network facility merge (#20008)
Undoing network facility merge (#20010)
Undoing network facility merge (#20753)
Undoing network facility merge (#21311)
Undoing network facility merge (#21720)
Undoing network facility merge (#21913)
Undoing network facility merge (#21993)
Undoing network facility merge (#22852)
Undoing network facility merge (#23006)
Undoing network facility merge (#23008)
Undoing network facility merge (#24731)
Undoing network facility merge (#26082)
Undoing network facility merge (#26253)
Undoing network facility merge (#27346)
Undoing ix facility deletion (#351)
Undoing ix facility deletion (#539)
Undoing ix facility deletion (#1173)
Undoing network facility deletion (#6138)
Undoing network facility deletion (#6521)
Undoing network facility deletion (#6574)
Undoing network facility deletion (#6895)
Undoing network facility deletion (#8321)
Undoing network facility deletion (#8536)
Undoing network facility deletion (#9290)
Undoing network facility deletion (#10377)
Undoing network facility deletion (#10539)
Undoing network facility deletion (#10644)
Undoing network facility deletion (#10804)
Undoing network facility deletion (#11940)
Undoing network facility deletion (#13533)
Undoing network facility deletion (#13997)
Undoing network facility deletion (#14334)
Undoing network facility deletion (#14678)
Undoing network facility deletion (#14788)
Undoing network facility deletion (#14805)
Undoing network facility deletion (#16142)
Undoing network facility deletion (#18977)
Undoing network facility deletion (#20286)
Undoing network facility deletion (#20616)
Undoing network facility deletion (#21348)
Undoing network facility deletion (#21831)
Undoing network facility deletion (#22208)
Undoing network facility deletion (#22535)
Undoing network facility deletion (#24054)
Undoing network facility deletion (#26232)
Undoing network facility deletion (#26493)
Undoing network facility deletion (#26858)
Undoing network facility deletion (#26934)
Undoing network facility deletion (#27138)

Log (#1244):

Undeleting facility Equinix Paris Pantin (PA4) (#1244)
======================
Undoing merge Equinix Paris Pantin (PA4) (#1244)
Undoing network facility merge (#12587)
Undoing network facility merge (#15739)
Undoing network facility merge (#17581)
Undoing network facility merge (#17725)
Undoing network facility merge (#18056)
Undoing network facility merge (#19732)
Undoing network facility merge (#22757)
Undoing network facility merge (#24295)
Undoing network facility merge (#25171)
Undoing ix facility deletion (#477)
Undoing network facility deletion (#547)
Undoing network facility deletion (#2612)
Undoing network facility deletion (#3611)
Undoing network facility deletion (#9909)
Undoing network facility deletion (#10919)
Undoing network facility deletion (#11956)
Undoing network facility deletion (#12323)
Undoing network facility deletion (#13829)
Undoing network facility deletion (#13959)
Undoing network facility deletion (#14333)
Undoing network facility deletion (#14514)
Undoing network facility deletion (#19673)
Undoing network facility deletion (#20615)
Undoing network facility deletion (#20771)
Undoing network facility deletion (#21288)
Undoing network facility deletion (#27596)

Log (#73):

Undeleting facility Equinix Paris Victor Hugo (PA5) (formerly TCY Par1) (#73)
======================
Undoing merge Equinix Paris Victor Hugo (PA5) (formerly TCY Par1) (#73)
Undoing network facility merge (#223)
Undoing network facility merge (#1383)
Undoing network facility merge (#1805)
Undoing network facility merge (#2424)
Undoing network facility merge (#5015)
Undoing network facility merge (#8544)
Undoing network facility merge (#9993)
Undoing network facility merge (#10760)
Undoing network facility merge (#15686)
Undoing network facility merge (#17687)
Undoing network facility merge (#24022)
Undoing ix facility merge (#157)
Undoing network facility deletion (#461)
Undoing network facility deletion (#946)
Undoing network facility deletion (#991)
Undoing network facility deletion (#3407)
Undoing network facility deletion (#3836)
Undoing network facility deletion (#6528)
Undoing network facility deletion (#8532)
Undoing network facility deletion (#12318)
Undoing network facility deletion (#13607)
Undoing network facility deletion (#13826)
Undoing network facility deletion (#14378)
Undoing network facility deletion (#18057)
Undoing network facility deletion (#20620)
Undoing network facility deletion (#23750)

Log (#842):

Undeleting facility Equinix Paris Condorcet (PA6) (formerly TCY Par3) (#842)
======================
Undoing merge Equinix Paris Condorcet (PA6) (formerly TCY Par3) (#842)
Undoing network facility merge (#7369)
Undoing network facility merge (#9821)
Undoing network facility merge (#10514)
Undoing network facility merge (#11049)
Undoing network facility merge (#16946)
Undoing network facility merge (#17768)
Undoing network facility merge (#19876)
Undoing network facility merge (#20068)
Undoing network facility merge (#21428)
Undoing network facility merge (#22843)
Undoing network facility merge (#23531)
Undoing network facility merge (#26213)
Undoing network facility merge (#27232)
Undoing ix facility merge (#1321)
Undoing ix facility deletion (#1283)
Undoing network facility deletion (#7268)
Undoing network facility deletion (#7706)
Undoing network facility deletion (#7771)
Undoing network facility deletion (#8533)
Undoing network facility deletion (#12319)
Undoing network facility deletion (#13827)
Undoing network facility deletion (#14340)
Undoing network facility deletion (#18058)
Undoing network facility deletion (#18103)
Undoing network facility deletion (#21782)
Undoing network facility deletion (#21947)
Undoing network facility deletion (#22068)
Undoing network facility deletion (#26784)
Undoing network facility deletion (#27137)
