### ISSUE TITLE
IXP renumbering

### ISSUE THREAD

**Issue by job** [peeringdb/admincom#8]
If we need to renumber an entire IXP from `A.B.C.x/24` to `D.E.F.x/23`, currently we have to ask 20c to do it for us.

This ticket was opened to ask for a tool https://github.com/peeringdb/peeringdb/issues/80 - current status is that it lacks documentation

**Comment by arnoldnipper** [comment]
done ... https://peeringdb.com/cp/peeringdb_server/commandlinetool/
