### ISSUE TITLE
Merge Duplicate Facility 2200 > 3076

### ISSUE THREAD

**Issue by NoelleKenny** [peeringdb/admincom#88]
Please merge 

https://www.peeringdb.com/fac/2200  (nextfort) to 
https://www.peeringdb.com/fac/3076 (H5)

H5 acquired NextForts datacenter:
http://h5datacenters.com/h5-phoenix-data-center-expansion.html

**Comment by arnoldnipper** [comment]
Merging facilities 2200
Merging NextFort (2200) ..
  - netfac NetworkFacility-netfac17032
  - netfac NetworkFacility-netfac23374 : connection already exists at target, skipping.
soft deleting NetworkFacility-netfac23374
soft deleting NextFort

**Comment by arnoldnipper** [comment]
Merging facilities 1109
Merging Herakles Datacenter (1109) ..
soft deleting Herakles Datacenter
