### ISSUE TITLE
Merge Duplicate Facility 1109 > 3359 

### ISSUE THREAD

**Issue by NoelleKenny** [peeringdb/admincom#89]
Please merge:

https://www.peeringdb.com/fac/1109 (Herakles Datacenter) > 
https://www.peeringdb.com/fac/3359 (QTS)

QTS acquired Herakles:
https://www.qtsdatacenters.com/company/news/2013/01/04/herakles-data-center-acquisition

**Comment by arnoldnipper** [comment]
Merging facilities 2200
Merging NextFort (2200) ..
  - netfac NetworkFacility-netfac17032
  - netfac NetworkFacility-netfac23374 : connection already exists at target, skipping.
soft deleting NetworkFacility-netfac23374
soft deleting NextFort
